export const actionLabel: Record<string, string> = {
  "workflow.deal_won": "Satış kapandı",
  "commission.paid": "Komisyon tahsil",
  "commission.from_pipeline": "Satış hattı komisyonu",
  "deal.create": "Anlaşma oluşturuldu",
  "deal.stage": "Anlaşma aşaması",
  "deal.update": "Anlaşma güncellendi",
  "payment_link.create": "Ödeme linki",
  "share.create": "Paylaşım linki",
  "ops.impersonate.start": "Ofis önizleme başladı",
  "ops.impersonate.stop": "Ofis önizleme bitti",
  "customer.create": "Müşteri eklendi",
  "customer.update": "Müşteri güncellendi",
  "customer.delete": "Müşteri silindi",
  "customer.reassign": "Müşteri devri",
  "customer_file.upload": "Müşteri dosyası yüklendi",
  "customer_file.delete": "Müşteri dosyası silindi",
  "match.save": "Eşleştirme kaydı",
  "demo.request": "Demo talebi",
  "demand.create": "Talep oluşturuldu",
  "demand.update": "Talep güncellendi",
  "property.create": "Portföy oluşturuldu",
  "property.update": "Portföy güncellendi",
  "property.status": "Portföy durumu değişti",
  "property.delete": "Portföy silindi",
  "property.reassign": "Portföy devri",
  "property.bulk_status": "Toplu portföy durumu",
  "property_media.upload": "Portföy medyası yüklendi",
  "valuation.create": "Değerleme oluşturuldu",
  "iys.upsert": "İYS izin kaydı",
  "task.create": "Görev oluşturuldu",
  "task.update": "Görev güncellendi",
  "task.complete": "Görev tamamlandı",
  "call.create": "Arama kaydı",
  "appointment.create": "Randevu oluşturuldu",
  "appointment.update": "Randevu güncellendi",
  "settings.update": "Ayarlar güncellendi",
  "portal.close": "Portal ilanı kapatıldı",
  "lead.capture.toggle": "Lead formu aç/kapat",
  "lead.capture.regenerate_token": "Lead form bağlantısı yenilendi",
  "kvkk.erasure": "KVKK silme talebi",
  "kvkk.purge": "KVKK verisi imha edildi",
  "integration.endeksa.save": "Endeksa entegrasyonu kaydedildi",
  "integration.endeksa.clear": "Endeksa entegrasyonu kaldırıldı",
  "integration.tapusor.save": "TapuSor entegrasyonu kaydedildi",
  "integration.tapusor.clear": "TapuSor entegrasyonu kaldırıldı",
  "platform_staff.add": "Platform ekibine eklendi",
  "platform_staff.invite": "Platform ekip daveti",
  "platform_staff.role_change": "Platform rol değişikliği",
  "platform_staff.deactivate": "Platform üyesi pasifleştirildi",
  "platform_staff.reactivate": "Platform üyesi aktifleştirildi",
  "sales.status": "Satış kaydı durumu",
  "sales.assign": "Satış kaydı ataması",
  "sales.convert": "Satış kaydı dönüştürüldü",
  "team.advisor_created": "Danışman eklendi",
  "team.member_updated": "Üye bilgisi güncellendi",
  "team.password_reset_sent": "Üyeye parola sıfırlama gönderildi",
  "team.invite_resent": "Davet yeniden gönderildi",
  "account.profile_updated": "Kullanıcı profili güncellendi",
  "account.password_changed": "Parola değiştirildi",
  "account.other_sessions_closed": "Diğer oturumlar kapatıldı",
  "billing.cancel_requested": "Abonelik iptal talebi",
  "billing.cancel_undone": "Abonelik iptal talebi geri alındı",
  "export.csv": "CSV dışa aktarma",
  "kvkk.request_created": "KVKK talebi açıldı",
  "kvkk.request_status": "KVKK talep durumu değişti",
};
export const HIGH_RISK_ACTIONS = [
  "customer.delete",
  "property.delete",
  "customer_file.delete",
  "kvkk.erasure",
  "kvkk.purge",
  "ops.impersonate.start",
  "ops.impersonate.stop",
  "platform_staff.role_change",
  "platform_staff.deactivate",
] as const;
export const MED_RISK_ACTIONS = [
  "settings.update",
  "customer.reassign",
  "property.reassign",
  "property.bulk_status",
  "portal.close",
  "lead.capture.toggle",
  "lead.capture.regenerate_token",
  "integration.endeksa.save",
  "integration.endeksa.clear",
  "integration.tapusor.save",
  "integration.tapusor.clear",
  "platform_staff.add",
  "platform_staff.invite",
  "platform_staff.reactivate",
  "sales.assign",
] as const;

export type RiskLevel = "yuksek" | "orta" | "dusuk";
export function riskOf(action: string): RiskLevel {
  if ((HIGH_RISK_ACTIONS as readonly string[]).includes(action)) return "yuksek";
  if ((MED_RISK_ACTIONS as readonly string[]).includes(action)) return "orta";
  return "dusuk";
}
