import {
  DEFAULT_TRIAL_DAYS,
  DEFAULT_TRIAL_GRACE_DAYS,
  MAX_MAINTENANCE_MESSAGE,
  MAX_TRIAL_DAYS,
  MAX_TRIAL_GRACE_DAYS,
  MIN_TRIAL_DAYS,
  MIN_TRIAL_GRACE_DAYS,
  PLATFORM_SETTING_KEYS,
} from "@/lib/platform-setting-keys";
import { TRY_DEFAULT_MAX_SHARE, TRY_MAX_SHARE_SETTING_KEY } from "@/lib/try-credits/constants";
import { parseMaxShare } from "@/lib/try-credits/config";
import { DEFAULT_LEAD_FORM_COPY } from "@/lib/legal-copy";
import { EMAIL_TEMPLATES, templateSettingKey } from "@/lib/email/templates";
import type { AnySettingDef } from "../types";
import { defineBool, defineEnum, defineInt, defineJson, defineNumber, defineSecret, defineString } from "./define";

/**
 * PLATFORM ayarlari. ILK DALGA KURALI: varsayilan = bugunku sabit (registry.test.ts kilitler), davranis degismez,
 * mevcut depolar (platform_settings) korunur, veri tasima YOK. `key` noktali ad; depo adi `storageKey`.
 */

const SUPER = { platformModule: "sistem", superAdminOnly: true } as const;

/** Konuya ait ayarların düzenlendiği bölüm sayfaları (merkez bunları bağlantı olarak gösterir). */
export const SYSTEM_HOME = { href: "/admin/sistem#ayarlar", label: "Sistem > Kayıt ve bakım" } as const;
export const BILLING_HOME = { href: "/admin/billing#ayarlar", label: "Abonelik & fatura > Ayarlar" } as const;

export const PORTAL_NAMES = ["sahibinden", "hepsiemlak", "zingat", "emlakjet"] as const;

const general: AnySettingDef[] = [
  defineBool({
    key: "platform.maintenance_mode",
    home: SYSTEM_HOME,
    storageKey: PLATFORM_SETTING_KEYS.maintenanceMode,
    legacyKeys: ["maintenance_mode"],
    default: false,
    category: "bayrak",
    label: "Bakım modu",
    description: "Açıkken ofis panelleri bakım ekranı gösterir.",
    impact: "Tüm ofis kullanıcıları bakım ekranını görür; yöneticiler etkilenmez. Kapatınca anında normale döner.",
    risk: "high",
    edge: true,
    cacheTags: ["settings:platform"],
  }),
  defineString({
    key: "platform.maintenance_message",
    home: SYSTEM_HOME,
    storageKey: PLATFORM_SETTING_KEYS.maintenanceMessage,
    legacyKeys: ["maintenance_message"],
    default: "",
    maxLength: MAX_MAINTENANCE_MESSAGE,
    multiline: true,
    category: "bayrak",
    label: "Bakım mesajı",
    description: "Bakım ekranında gösterilen kısa açıklama.",
    impact: "Yalnız bakım modu açıkken kullanıcıya görünür.",
    edge: true,
  }),
  defineBool({
    key: "platform.registration_open",
    home: SYSTEM_HOME,
    storageKey: PLATFORM_SETTING_KEYS.registrationOpen,
    legacyKeys: ["registration_open"],
    default: true,
    category: "bayrak",
    label: "Yeni kayıt açık",
    description: "Kapatıldığında yeni ofis kaydı alınmaz.",
    impact: "Kayıt sayfası ve signUp kapalı mesajı gösterir; mevcut hesaplar giriş yapabilir.",
    risk: "high",
    edge: true,
  }),
  defineInt({
    key: "billing.default_trial_days",
    home: BILLING_HOME,
    storageKey: PLATFORM_SETTING_KEYS.defaultTrialDays,
    legacyKeys: ["default_trial_days"],
    default: DEFAULT_TRIAL_DAYS,
    min: MIN_TRIAL_DAYS,
    max: MAX_TRIAL_DAYS,
    unit: "gün",
    category: "faturalama",
    label: "Varsayılan deneme süresi",
    description: "Yeni kayıt ve demo dönüşümünde uygulanan deneme günü.",
    impact: "Yalnız bundan sonra açılan denemeleri etkiler; sürmekte olan denemeler değişmez. SQL platform_default_trial_days() ayrıca korunur.",
  }),
  defineInt({
    key: "billing.trial_grace_days",
    home: BILLING_HOME,
    storageKey: PLATFORM_SETTING_KEYS.trialGraceDays,
    default: DEFAULT_TRIAL_GRACE_DAYS,
    min: MIN_TRIAL_GRACE_DAYS,
    max: MAX_TRIAL_GRACE_DAYS,
    unit: "gün",
    category: "faturalama",
    label: "Deneme sonrası tolerans",
    description: "Deneme bitip ödeme yapılmazsa ofis bu süre sonunda otomatik askıya alınır.",
    impact: "Süreyi kısaltmak, ödeme yapmamış ofislerin daha erken askıya alınmasına yol açar. Ödeme yapılınca askı kalkar.",
    risk: "high",
  }),
  defineBool({
    key: "billing.auto_renew_enabled",
    home: BILLING_HOME,
    default: false,
    truthy: "true-false",
    category: "faturalama",
    label: "Otomatik yenileme (kart)",
    description: "Kayıtlı karttan otomatik abonelik yenileme yönetici bayrağı. Kapalıyken ödeme kod yolu çalışmaz.",
    impact: "Açılırsa rıza veren ofislerin kartından yenileme tahsilatı denenir. Açmadan önce sözleşme ve rıza metni onaylanmalıdır.",
    risk: "high",
  }),
  defineBool({
    key: "billing.plan_change_proration_enabled",
    home: BILLING_HOME,
    default: false,
    category: "faturalama",
    label: "Oransal paket yükseltme / planlı düşürme",
    description: "Aktif ücretli abonelikte üst pakete kalan gün oranında fark faturasıyla geçiş; daha ucuz pakete geçiş dönem sonunda uygulanır (iade yok).",
    impact: "Açılırsa ofisler Paket & ödeme ekranında oransal yükseltme ve planlı düşürme görür; aktif aboneliğin tam fiyatlı paket değişimi kapanır. Önce 20261007001000 ve 20261007001010 migration'ları uygulanmalıdır; SQL de bu ayarı kontrol eder.",
    risk: "high",
  }),
  defineBool({
    key: "billing.pause_enabled",
    home: BILLING_HOME,
    default: false,
    category: "faturalama",
    label: "Abonelik duraklatma",
    description: "Ofis sahibi, aktif aboneliğini ayarlanan en çok gün kadar duraklatabilir (yılda 1 kez). Duraklatmada veri salt-okunur olur; dönem bitişi duraklatma süresi kadar uzar.",
    impact: "Açılırsa ofis sahipleri Paket & ödeme ekranında duraklatma görür. Duraklatılmış ofiste yazma işlemleri kapanır; faturalama ve gecikme kontrolleri durur. Önce 20261007001000 migration'ı uygulanmalıdır; SQL de bu ayarı kontrol eder.",
    risk: "high",
  }),
  defineInt({
    key: "billing.pause_max_days",
    home: BILLING_HOME,
    default: 30,
    min: 1,
    max: 90,
    unit: "gün",
    category: "faturalama",
    label: "Duraklatma azami süresi",
    description: "Bir duraklatmanın en uzun süresi (gün). Yılda en çok 1 duraklatma yapılabilir.",
    impact: "Yalnız bundan sonra başlayan duraklatmalara uygulanır; süren duraklatmalar planlanan bitişte devam eder.",
  }),
  defineNumber({
    key: "try_credit.max_invoice_share",
    home: BILLING_HOME,
    storageKey: TRY_MAX_SHARE_SETTING_KEY,
    default: TRY_DEFAULT_MAX_SHARE,
    min: 0.0001,
    max: 1,
    parse: parseMaxShare,
    category: "emlakfiyati",
    label: "TL kredinin fatura payı üst sınırı",
    description: "Tek faturada TL kredinin KDV dahil toplamdaki en yüksek payı (0-1). 1 = tam kredi ile ödeme açılır.",
    impact: "1 yapılırsa iyzico'suz tam kredi ödemesi mümkün olur. Değişiklik yeni faturalarda geçerlidir (önbellek 60 sn).",
    risk: "high",
    cacheTags: ["try-credit-config"],
  }),
];

const security: AnySettingDef[] = [
  defineBool({
    key: "platform.mfa_enforced",
    default: false,
    category: "guvenlik",
    label: "Platform personeli için zorunlu iki adımlı doğrulama",
    description: "Veritabanı kapılarının personelden AAL2 istemesi. Ortam değişkeni PLATFORM_MFA_ENFORCEMENT ile birlikte tutarlı olmalıdır.",
    impact: "Yayın öncesi açılacak; şu an kapalı tutulur. Tutarsız durumda (env açık, bu ayar kapalı) /admin üstünde uyarı görünür.",
    risk: "high",
    editMode: "locked",
    lockedReason: "Zorunlu MFA yayın planına göre ayrıca açılır; bu merkezden değiştirilemez. Durum yalnız gösterilir.",
    envFallback: "PLATFORM_MFA_ENFORCEMENT",
  }),
];

const BRIDGES: { key: string; storageKey: string; category: AnySettingDef["category"]; label: string; description: string; impact: string; href: string }[] = [
  { key: "billing.plan_definitions", storageKey: "billing.plan_definitions", category: "faturalama", label: "Plan tanımları ve fiyatlar", description: "Plan fiyatları, koltuk ve özellik sınırları (yönetici geçersiz kılmaları).", impact: "Yeni satışları ve yenilemeleri etkiler; mevcut kilitli fiyatlar korunur.", href: "/admin/billing/planlar" },
  { key: "billing.seat_settings", storageKey: "billing.seat_settings", category: "faturalama", label: "Koltuk ayarları", description: "Ek koltuk fiyatlandırma ve dönem ayarları.", impact: "Ek koltuk siparişlerinin tutarını etkiler.", href: "/admin/billing/planlar" },
  { key: "ef.tariff", storageKey: "ef.tariff", category: "emlakfiyati", label: "EmlakFiyatı kontör tarifesi", description: "İşlem başına kontör maliyeti.", impact: "Yeni değerleme ve rapor işlemlerinin kontör bedelini değiştirir.", href: "/admin/ef-kontor" },
  { key: "ef.packs", storageKey: "ef.packs", category: "emlakfiyati", label: "Kontör paketleri", description: "Satışa açık kontör paketleri.", impact: "Ofislerin satın alabileceği paketleri değiştirir.", href: "/admin/ef-kontor" },
  { key: "ef.welcome_units", storageKey: "ef.welcome_units", category: "emlakfiyati", label: "Hoş geldin kontörü", description: "Yeni ofise verilen kontör miktarı.", impact: "Yalnız bundan sonra açılan ofisleri etkiler.", href: "/admin/billing/planlar" },
  { key: "ef.welcome_since", storageKey: "ef.welcome_since", category: "emlakfiyati", label: "Hoş geldin kontörü başlangıç tarihi", description: "Hoş geldin kontörünün geçerli olduğu başlangıç.", impact: "Tarihten önce açılan ofisler kontör almaz.", href: "/admin/billing/planlar" },
  { key: "ef.wholesale", storageKey: "ef.wholesale", category: "emlakfiyati", label: "Toptan kontör maliyeti", description: "Kontör ekonomisi (maliyet) hesabında kullanılan toptan birim.", impact: "Muhasebe ekranındaki kontör kârlılığı hesabını etkiler.", href: "/admin/muhasebe" },
  { key: "ai.credit_cost_table", storageKey: "ai.credit_cost_table", category: "ai", label: "AI kredi maliyet tablosu", description: "AI özelliklerinin kredi bedelleri.", impact: "Ofislerin AI kullanımında düşen kredi miktarını değiştirir.", href: "/admin/ai-kullanim" },
];

const bridges: AnySettingDef[] = BRIDGES.map((b) =>
  defineJson({
    key: b.key,
    storageKey: b.storageKey,
    default: "",
    category: b.category,
    label: b.label,
    description: b.description,
    impact: b.impact,
    editHref: b.href,
    permission: SUPER,
  }),
);

const GROWTH_FLAGS = [
  { storageKey: "growth_referral_enabled", key: "growth.referral_enabled", label: "Referans (davet) programı", description: "Ofis davet ve ödül programı bayrağı." },
  { storageKey: "growth_partner_enabled", key: "growth.partner_enabled", label: "Ortak programı", description: "Ortak (partner) komisyon programı bayrağı." },
  { storageKey: "growth_cash_payout_enabled", key: "growth.cash_payout_enabled", label: "Nakit ortak ödemesi", description: "Ortak ödemelerinin nakit yapılması (ortak programından ayrı)." },
] as const;

const growth: AnySettingDef[] = GROWTH_FLAGS.map((g) =>
  defineBool({
    key: g.key,
    storageKey: g.storageKey,
    default: false,
    category: "buyume",
    label: g.label,
    description: g.description,
    impact: "Kapalıyken ilgili program ekranları ve ödül hesapları çalışmaz.",
    risk: "high",
    editMode: "bridge",
    editHref: "/admin/growth",
  }),
);

const integrations: AnySettingDef[] = [
  defineSecret({
    key: "ai.openai_api_key",
    storageKey: "openai_api_key",
    legacyKeys: ["openai_api_key"],
    maxLength: 256,
    minLength: 20,
    pattern: /^sk-/,
    patternMessage: "Geçersiz anahtar biçimi (sk- ile başlamalı).",
    category: "ai",
    label: "OpenAI API anahtarı",
    description: "Platformun AI çağrıları için kullandığı anahtar. Veritabanında şifreli saklanır; ortam değişkeni OPENAI_API_KEY yedektir.",
    impact: "Değişiklik tüm AI özelliklerini (asistan, ilan metni, değerleme açıklaması) bir sonraki çağrıda etkiler. Silinirse ortam anahtarına düşülür.",
    envFallback: "OPENAI_API_KEY",
  }),
  defineString({
    key: "notify.netgsm_usercode",
    storageKey: "netgsm_usercode",
    default: "",
    maxLength: 64,
    category: "bildirim",
    label: "Netgsm kullanıcı kodu",
    description: "Platform yedek SMS hesabı kullanıcı kodu.",
    impact: "Platform SMS gönderimi bu hesapla yapılır.",
    editMode: "bridge",
    editHref: "/admin/sistem",
    envFallback: "NETGSM_USERCODE",
  }),
  defineSecret({
    key: "notify.netgsm_password",
    storageKey: "netgsm_password",
    maxLength: 256,
    category: "bildirim",
    label: "Netgsm parolası",
    description: "Platform yedek SMS hesabı parolası. Şifreli saklanır.",
    impact: "Yanlış parola SMS gönderimini durdurur. Kullanıcı kodu ve başlık /admin/sistem ekranındadır.",
    envFallback: "NETGSM_PASSWORD",
  }),
  defineString({
    key: "notify.netgsm_msgheader",
    storageKey: "netgsm_msgheader",
    default: "",
    maxLength: 11,
    category: "bildirim",
    label: "Netgsm mesaj başlığı",
    description: "Onaylı SMS başlığı (1-11 karakter).",
    impact: "Gönderilen SMS'lerde gönderici adı olarak görünür.",
    editMode: "bridge",
    editHref: "/admin/sistem",
    envFallback: "NETGSM_MSGHEADER",
  }),
  defineString({
    key: "notify.whatsapp_api_url",
    storageKey: "whatsapp_api_url",
    default: "",
    maxLength: 512,
    category: "bildirim",
    label: "WhatsApp API adresi",
    description: "İzinli sağlayıcı alan adına sahip HTTPS adresi (SSRF koruması).",
    impact: "WhatsApp gönderimi bu adrese yapılır.",
    editMode: "bridge",
    editHref: "/admin/sistem",
    envFallback: "WHATSAPP_API_URL",
  }),
  defineSecret({
    key: "notify.whatsapp_api_token",
    storageKey: "whatsapp_api_token",
    maxLength: 4096,
    category: "bildirim",
    label: "WhatsApp API anahtarı",
    description: "WhatsApp sağlayıcı erişim anahtarı. Şifreli saklanır.",
    impact: "Yanlış anahtar WhatsApp gönderimini durdurur. API adresi /admin/sistem ekranındadır.",
    envFallback: "WHATSAPP_API_TOKEN",
  }),
  defineEnum({
    key: "efatura.provider",
    storageKey: "efatura_provider",
    default: "",
    options: [
      { value: "", label: "Tanımsız (ortam değişkeni)" },
      { value: "parasutu", label: "Paraşüt" },
      { value: "logo", label: "Logo" },
      { value: "custom", label: "Özel" },
    ],
    category: "entegrasyon",
    label: "E-fatura sağlayıcı",
    description: "Fatura kesim entegrasyonu sağlayıcısı.",
    impact: "Yanlış sağlayıcı fatura oluşturmayı başarısız kılar.",
    risk: "high",
    envFallback: "EFATURA_PROVIDER",
  }),
  defineString({
    key: "efatura.api_url",
    storageKey: "efatura_api_url",
    default: "",
    maxLength: 512,
    category: "entegrasyon",
    label: "E-fatura API adresi",
    description: "Sağlayıcı API tabanı (izinli alan adı denetimi okuma anında yapılır).",
    impact: "İzinli olmayan adres e-fatura entegrasyonunu kapalı sayar.",
    risk: "high",
    envFallback: "EFATURA_API_URL",
  }),
  defineSecret({
    key: "efatura.api_key",
    storageKey: "efatura_api_key",
    maxLength: 1024,
    category: "entegrasyon",
    label: "E-fatura API anahtarı",
    description: "E-fatura sağlayıcı anahtarı. Şifreli saklanır.",
    impact: "Yanlış anahtar fatura kesimini durdurur.",
    envFallback: "EFATURA_API_KEY",
  }),
  defineString({
    key: "efatura.company_vkn",
    storageKey: "efatura_company_vkn",
    default: "",
    maxLength: 11,
    category: "entegrasyon",
    label: "E-fatura firma VKN",
    description: "Faturayı kesen firmanın vergi kimlik numarası.",
    impact: "Kesilen faturalardaki satıcı kimliğidir.",
    risk: "high",
    envFallback: "EFATURA_COMPANY_VKN",
  }),
];

const portals: AnySettingDef[] = PORTAL_NAMES.flatMap((p) => [
  defineSecret({
    key: `portal.${p}.api_key`,
    storageKey: `${p}_api_key`,
    maxLength: 4096,
    category: "entegrasyon",
    label: `${p[0].toUpperCase()}${p.slice(1)} API anahtarı`,
    description: "Portal ilan yayını için kurumsal sözleşme anahtarı. Şifreli saklanır. Adres ve ofis kimliği /admin/sistem ekranındadır.",
    impact: "Yanlış anahtar bu portala ilan yayınını durdurur.",
    envFallback: `${p.toUpperCase()}_API_KEY`,
  }),
  defineSecret({
    key: `portal.${p}.api_secret`,
    storageKey: `${p}_api_secret`,
    maxLength: 4096,
    category: "entegrasyon",
    label: `${p[0].toUpperCase()}${p.slice(1)} API gizli anahtarı`,
    description: "Portal gizli anahtarı (varsa). Şifreli saklanır.",
    impact: "Yanlış değer bu portala ilan yayınını durdurur.",
    envFallback: `${p.toUpperCase()}_API_SECRET`,
  }),
  defineString({
    key: `portal.${p}.agency_id`,
    storageKey: `${p}_agency_id`,
    default: "",
    maxLength: 512,
    category: "entegrasyon",
    label: `${p[0].toUpperCase()}${p.slice(1)} ofis kimliği`,
    description: "Portalın ofise verdiği kurumsal kimlik.",
    impact: "Portal ilan yayınlarında ofis tanımlayıcısı olarak gönderilir.",
    editMode: "bridge",
    editHref: "/admin/sistem",
    envFallback: `${p.toUpperCase()}_AGENCY_ID`,
  }),
  defineString({
    key: `portal.${p}.base_url`,
    storageKey: `${p}_base_url`,
    default: "",
    maxLength: 512,
    category: "entegrasyon",
    label: `${p[0].toUpperCase()}${p.slice(1)} API adresi`,
    description: "Sözleşmede verilen HTTPS API tabanı (izinli alan adı denetimi yazımda yapılır).",
    impact: "Yanlış adres bu portala yayını durdurur.",
    risk: "high",
    editMode: "bridge",
    editHref: "/admin/sistem",
    envFallback: `${p.toUpperCase()}_BASE_URL`,
  }),
]);

/**
 * Yasal metinler (başvuru formu onay/aydınlatma/pazarlama). Varsayılan = legal-copy.ts sabitleri (davranış değişmez);
 * değişiklik rıza kanıtı sürümüne metin izi olarak yansır (buildLeadConsentVersion). Metin sorumluluğu ofis/şirket sahibindedir.
 */
export const LEGAL_HOME = { href: "/admin/ayarlar/yasal", label: "Ayarlar > Yasal metinler" } as const;
const legal: AnySettingDef[] = [
  defineString({
    key: "legal.lead_consent_text",
    home: LEGAL_HOME,
    default: DEFAULT_LEAD_FORM_COPY.consent,
    maxLength: 300,
    minLength: 10,
    multiline: true,
    category: "uyum",
    label: "Başvuru formu zorunlu onay metni",
    description: "Ofis başvuru formundaki zorunlu kişisel veri onay kutusunun metni.",
    impact: "Yeni başvurularda gösterilir; rıza kanıtındaki sürüm metnin iziyle değişir. Eski kanıtlar etkilenmez.",
    risk: "high",
  }),
  defineString({
    key: "legal.lead_notice_text",
    home: LEGAL_HOME,
    default: DEFAULT_LEAD_FORM_COPY.notice,
    maxLength: 300,
    minLength: 10,
    multiline: true,
    category: "uyum",
    label: "Başvuru formu aydınlatma satırı",
    description: "Onay kutusunun üstündeki, aydınlatma metnine yönlendiren bilgi satırı.",
    impact: "Yeni başvurularda gösterilir; rıza kanıtındaki sürüm metnin iziyle değişir.",
    risk: "high",
  }),
  defineString({
    key: "legal.lead_marketing_text",
    home: LEGAL_HOME,
    default: DEFAULT_LEAD_FORM_COPY.marketing,
    maxLength: 300,
    minLength: 10,
    multiline: true,
    category: "uyum",
    label: "Başvuru formu isteğe bağlı pazarlama izni metni",
    description: "Ayrı, varsayılan işaretsiz pazarlama izni kutusunun metni.",
    impact: "Yeni başvurularda gösterilir; izin kanıtı ayrı sürüm ekiyle saklanır.",
    risk: "high",
  }),
];

/**
 * İşlemsel e-posta şablonları (konu + gövde). Varsayılan = `src/lib/email/templates.ts`. Gönderim yalnız e-posta kanalı
 * (RESEND_API_KEY + EMAIL_FROM) açıkken yapılır; kanal kapalıyken metinler düzenlenebilir ama kullanılmaz.
 */
export const EMAIL_HOME = { href: "/admin/ayarlar/eposta", label: "Ayarlar > E-posta şablonları" } as const;
const emailTemplates: AnySettingDef[] = EMAIL_TEMPLATES.flatMap((t) => [
  defineString({
    key: templateSettingKey(t.key, "subject"),
    home: EMAIL_HOME,
    default: t.defaultSubject,
    maxLength: 200,
    minLength: 3,
    category: "bildirim",
    label: `${t.label}: e-posta konusu`,
    description: `Değişkenler: ${t.variables.map((v) => `{${v}}`).join(", ")}.`,
    impact: `Bu şablonla giden e-postaların konu satırı değişir. Gönderen akış: ${t.usedBy}`,
  }),
  defineString({
    key: templateSettingKey(t.key, "body"),
    home: EMAIL_HOME,
    default: t.defaultBody,
    maxLength: 4000,
    minLength: 10,
    multiline: true,
    category: "bildirim",
    label: `${t.label}: e-posta gövdesi`,
    description: `Düz metin. Değişkenler: ${t.variables.map((v) => `{${v}}`).join(", ")}.`,
    impact: `Bu şablonla giden e-postaların metni değişir. Gönderen akış: ${t.usedBy}`,
  }),
]);

export const PLATFORM_SETTING_DEFS: readonly AnySettingDef[] = [
  ...general,
  ...security,
  ...legal,
  ...growth,
  ...bridges,
  ...integrations,
  ...portals,
  ...emailTemplates,
];